config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'


  resources :users
  resources :boards do
  	member do
  		put 'add_image'
  		put 'remove_image'
  	end
  end
  resources :images, except: [:edit, :update, :new]

  get 'home/index' => 'home#index', as: 'home'

  get 'sessions/new' => 'sessions#new', as: 'login'
  post 'sessions'    => 'sessions#create'
  delete 'sessions'  => 'sessions#destroy'

  get 'boards/:id/:width/:height' => 'boards#random', as: 'random'
  
end

app/models/bing_wrapper.rb
# Sets up the Bing image search api and set a method to search
class BingWrapper

	def self.search(search_input)
		# input api key and set how many images to return
		bing_image = Bing.new(ENV["BING_API_KEY"], 25, 'Image')
		search_string = search_input  
		result = bing_image.search("#{search_string}")
		parsed_result = result[0][:Image]
	end

end

app/models/bitly_wrapper.rb
class BitlyWrapper

	def self.short(url)
		bitly = Bitly.new(ENV["BITLY_USERNAME"], ENV["BITLY_API_KEY"])
		bitly_result = bitly.shorten(url)
		shortened_url = bitly_result.short_url
	end

end

app/models/board.rb
class Board < ActiveRecord::Base
	has_and_belongs_to_many :images
	belongs_to :user

	validates :name, :theme, presence: true

	def add_image(image)
		self.images.push(image)
	end

	def remove_image(image)
		self.images.destroy(image)
	end

end

app/models/image.rb
class Image < ActiveRecord::Base

	has_and_belongs_to_many :boards

	validates_presence_of :title, :imgurl, :width, :height, :filesize

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, presence: true, uniqueness: true
	validates_presence_of :first_name
	has_many :boards, dependent: :destroy
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

# 
  helper_method :current_user

  def authenticate
    redirect_to login_path unless session[:current_user_id]
  end

  def current_user
   	User.find(session[:current_user_id]) if session[:current_user_id]
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

	# before_action :authenticate

	def index
		@boards = Board.all
		# @user = current_user
	end

	def show
		@board = Board.find(params[:id])
		# @current_user = current_user
	end

	def new 
		if session[:current_user_id]
			@board = Board.new
		else
			redirect_to login_path
			flash[:new_board_error] = "Please login or signup in order to create a new board."
		end
	end

	def create
		@board = Board.new(board_params)
		@board.user_id = session[:current_user_id]
		if @board.save
			redirect_to @board
		else
			render :new
		end
	end

	def edit
		@board = Board.find(params[:id])
	end

	def update
		@board = Board.find(params[:id])
		if @board.update(board_params)
			redirect_to @board
		else
			render :edit
		end
	end

	def destroy
		@board = Board.find(params[:id])
		@board.destroy
		redirect_to @board
	end

	def add_image
		board = Board.find(params[:id])
		image = Image.find(params[:image_id])
		board.add_image(image)
		redirect_to board_path(board)
	end

	def remove_image
		board = Board.find(params[:id])
		image = Image.find(params[:image_id])
		board.remove_image(image)
		redirect_to board_path(board)
	end

#Method to generate custom placeholder link with random image, uses Cloudinary and Open URI
	def random
		#finding the board ID
		@board = Board.find(params[:id])
		#@url_array creates array of all of urls from all images on the board
		@url_array = @board.images.map do |image|
			image.imgurl
		end
		#@url selects a random image url from the @urls array
		@url = @url_array.sample
		#uploads random url to the Cloudinary cloud and
		#["url"] selects the newly resized url from the hash as @cloud)_url
		@cloud_url = Cloudinary::Uploader.upload(@url, :width => params[:width], :height => params[:height], :crop => :fill)["url"]
		#open/.read - opens the image url and reads content returning a string
		#send_data sends the data to browser
		send_data open(@cloud_url).read
	end


	private

	def board_params
		params.require(:board).permit(:name, :theme, :public, :user)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def index
		@images = BingWrapper.search(params[:search])
		if session[:current_user_id]
			@boards = User.find(session[:current_user_id]).boards
		end
	end

	def show
		@image = Image.find(params[:id])
	end

	def create
		board = Board.find(params[:board_id])
		if params["selected_images"] == nil
			flash[:uncheck_error] = "Please select at least one image to add to your board."
			redirect_to home_path
		else
			params["selected_images"].each do |image|
				image_obj =  Image.create(image_params(image))
				board.add_image(image_obj)
			end
			redirect_to board_path(board)
		end
	end

	def destroy
		board = Board.find(params[:id])
		if params["selected_images"] == nil
			redirect_to board_path(board)
		else
			params["selected_images"].each do |image|
				img = Image.find(image)
				img.destroy
			end
			redirect_to board_path(board)
		end
	end

	private

	def image_params(image_name)
		params.require(image_name).permit(:title, :imgurl, :width, :height, :filesize)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		if session[:current_user_id]
			redirect_to home_path
		end
	end

	def create
		@user = User.find_by(username: params[:username])
		if @user && @user.authenticate(params[:password])
			session[:current_user_id] = @user.id
			redirect_to user_path(@user)
		else
			flash[:login_error] = "That username password combo does not match our records. Please try again, sign-up, or continue as guest."
			render :new
		end
	end

	def destroy
		session[:current_user_id] = nil
		flash[:logout] = "You have successfully logged out"
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end
	
	def show
		@user = User.find(params[:id])
		@current_user = current_user
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user_id = session[:current_user_id]
		if @user.save
			session[:current_user_id] = @user.id
			redirect_to @user
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
		if @user != current_user
			redirect_to @user
		end
	end

	def update
		@user = User.find(params[:id])
		if @user != current_user
			redirect_to users_path
		else
			if @user.update(user_params)
				redirect_to @user
			else
				render :edit
			end
		end
	end

	def destroy
		@user = User.find(params[:id])

		# might not need the below statement, because can't get to edit page unless logged in.
		# to close session add:  session[:current_user_id] = nil
		if @user != current_user
			redirect_to users_path
		else
			@user.destroy
			session[:current_user_id] = nil
			redirect_to(users_path)

		end
	end

	private 
	def user_params
		params.require(:user).permit(:username, :first_name, :last_name, :avatar, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.erb
<!-- makes it so that only private boards are seen when logged in and public boards are always seen -->
	<% if board.user == current_user  %>
			<h2><%= link_to "#{board.name}", board_path(board) %></h2>
			<p>created by: <%= board.user.username %></p>
	<% elsif board.public == true %>
			<h2><%= link_to "#{board.name}", board_path(board) %></h2>
			<p>created by: <%= board.user.username %></p>
	<% end %>

app/views/boards/_buttons.html.erb
<% if buttons.include?(:new_board) %>
	<%= button_to "Create a New Board", new_board_path, method: :get %>
<% end %>

<% if buttons.include?(:edit_board) %>
	<%= button_to "Edit Information", edit_board_path, method: :get %>
<% end %>

<% if buttons.include?(:find_image) %>
	<%= button_to "Find Images", home_path, method: :get %>
<% end %>

<% if buttons.include?(:delete_board) %>
	<%= button_to "Delete Board", board_path, method: :delete %>
<% end %>

app/views/boards/_form.html.erb
<%= form_for @board do |f| %>
<div class="input">
  <%= f.label :name, "Board Name:" %>
  <%= f.text_field :name %>
</div>

<div class="input">
  <%= f.label :theme, "Project Theme:" %>
  <%= f.text_field :theme %>
</div>

<div class="input">
  <h4>Board Privacy Settings:</h4>
  <%= f.radio_button(:public, true) %>  
  <%= f.label(:public, "Public") %>

  <%= f.radio_button(:public, false) %>
  <%= f.label(:public, "Private") %>
</div>

	<%= f.submit 'Create My Board', :id=>"submit" %>
<% end %>

app/views/boards/edit.html.erb
<div class="form" id="signup">
	<h1>Edit Board Info</h1>

<% if @board.errors.any? %>
    <h3 style="color:red">Please fix the appropriate fields:</h3>
<% end %>

<hr>
	<%= render 'form' %>
</div>

app/views/boards/index.html.erb
<div class="main_content all_boards">
	<h1>All Boards</h1>
	
	<!-- buttons is an arbitrary word. means in this partial view please include these elements -->
	<%= render partial: 'buttons', locals: {buttons: [:new_board]} %>
	
	<div id="boards_block">
		<!-- renders a list of all the boards -->
		<%= render @boards %>
	</div>
</div>

app/views/boards/new.html.erb
<div class="form" id="signup">
	<h1>Create a New Board</h1>

	<!-- displays the errors if user doesn't enter the information correctly, maybe remove the text that appears and just just have the box highlight red if the field needs to be fixed -->
	<% if @board.errors.any? %>
	    <h3 style="color:red">Please fix the appropriate fields:</h3>
	<% end %>
	
	<hr>
		<%= render 'form'%>
</div>

app/views/boards/show.html.erb
<div class="main_content board_show">

	<div id="board_info">
		<h1>
			<%= @board.name %>
		</h1>
	
		<!-- board information contained in this block -->
		<p>
			<span>Theme:</span> <%= @board.theme %><br>
			<span>Created by:</span> <%= @board.user.first_name %> <%= @board.user.last_name %><br>
			<% if @board.public == true %>
				This board is public.
			<% else %>
				This Board is private.
			<% end %>
		</p>
	</div>

	<hr>

	<div id="instructions">
		<p>
			Use the link below to randomly generate an image from your board onto your project. Just add your dimensions into the example url. A new image will be displayed with each reload.
		</p>

		<h2>
			<span>Working example:</span> https://placeholdr-app.herokuapp.com/boards/<%= params[:id] %>/<span class="measurement">200</span>/<span class="measurement">200</span>
		</h2>
		
		<h2>
			<span>Template:</span> https://placeholdr-app.herokuapp.com/boards/<%= params[:id] %>/<span class="measurement">length</span>/<span class="measurement">width</span>
		</h2>
	</div>
	
	<hr>

<!-- //////////////////////////////////////////////////////////////////////////////// -->

	<h2 class="boards_right">Click an image to generate a color scheme based off of its dominant colors.</h2>

		<% if @board.user == current_user %>
			<!-- if the logged in user is viewing a board they made, they will be able to see the find more images and edit board info button -->
			<div class="button_block">
					<%= render partial: 'buttons', locals: {buttons: [:edit_board, :find_image, :delete_board]} %>
			</div>

			<br class="vital">

			<div id="board_images_block">
					
				<%= form_tag(image_path, :method => "delete") do %>
					<% @board.images.each_with_index do |image, index| %> 
						
						<div class="board_image">

							<%= link_to(image_path(image)) do %>
								<img src="<%= image.imgurl %>" class="board_single_image">
							<% end %>

							<div class="url_container">
								Copy Image URL: <input type="text" name="url" value="<%= image.imgurl %>" readonly>
								<%= hidden_field image.id, :value => image.id %>	
							</div>
							
							Select Image: <%= check_box_tag("selected_images[]", image.id) %>
							
							<br>
						</div>
					<% end %>

					<hr>

					<div class="button_block">
						<% if @board.images.count > 0 %>
							<span class="search_submit"><%= submit_tag("Delete Selected Images") %></span>
						<% end %>
					</div>

				<% end %>

			</div>

		<% else %>

			<br class="vital">
	
			<div class="logged_out" id="board_images_block">
				<!-- code block adds the images that belong to that specific board to the show view  -->
				<% @board.images.each do |image| %> 
					<div class="board_image">
						<!-- makes the image a link to that images image show page -->
						<%= link_to(image_path(image)) do %>
							<img src="<%= image.imgurl %>" class="board_single_image">
						<% end %>
							
						<div class="url_container">
							Copy Image URL: <input type="text" name="url" value="<%= image.imgurl %>" readonly>
							<%= hidden_field image.id, :value => image.id %>	
						</div>	
					</div>
				<% end %>

			</div>

		<% end %>
</div>

app/views/home/_search.html.erb
<%= form_tag images_path, method: "get" do %>
	<%= label_tag "Find Images:" %>
	<%= text_field_tag "search" %>
	<span class="search_submit"><%= submit_tag("Search") %></span>
<% end %>

app/views/home/index.html.erb
<div class="main_content search">
	<% if flash[:uncheck_error] %>
		<p class="uncheck_error"><%= flash[:uncheck_error] %></p>
	<% end %>
	<%= render 'search' %>
</div>

app/views/images/_images.html.erb
<div class="left">
	<img src="<%= image[:MediaUrl] %>">
	<div class="url_box">
		<span>Image URL:</span>
		<input type="text" name="url" value="<%= image[:MediaUrl] %>" readonly>
	</div>
</div>

<div class="right">
	<p>
		<span>Image Title:</span> <%= image[:Title] %><br>
		<span>Width:</span> <%= image[:Width] %><br> 
		<span>Height:</span> <%= image[:Height] %><br>
		<span>File Type:</span> <%= image[:ContentType] %><br>

		<% if logged_in %>
			<span>Select Image:</span> <%= check_box_tag("selected_images[]", "image#{index}") %>
							<%= hidden_field "image#{index}", :title, :value => image[:Title] %>
							<%= hidden_field "image#{index}", :imgurl, :value => image[:MediaUrl] %>
							<%= hidden_field "image#{index}", :width, :value => image[:Width] %>
							<%= hidden_field "image#{index}", :height, :value => image[:Height] %>
							<%= hidden_field "image#{index}", :filesize, :value => image[:FileSize] %>
		<% end %>
	</p>
</div>

app/views/images/index.html.erb
<div class="main_content images">
	<h1>Search Results for: <%= params[:search] %></h1>
	<div id="all_images">
		<% if session[:current_user_id] %>
			
			<%= form_tag(images_path, :method => "post") do %>				
				<% @images.each_with_index do |image, index| %>
					<div class="single_image">
						
						<%= render partial: 'images', locals: {image: image, index: index, logged_in: true } %>

						<br class="vital">
						<hr>	
					</div>
				<% end %>
				<h4>Select Cork Board:</h4>
				<p>Please select at least one image to add to your board.</p>			
				<%= collection_select(nil, :board_id, @boards, :id, :name) %>
				<span class="search_submit"><%= submit_tag("Save Images") %></span>
			<% end %>

		<% else %>

			<% @images.each_with_index do |image, index| %>
				<div class="single_image">
					<%= render partial: 'images', locals: {image: image, index: index, logged_in: false } %>
						
					<br class="vital">
					<hr>	
				</div>
			<% end %>	
		</div>

	<% end %>


</div>

app/views/images/show.html.erb
<div class="main_content images" id="image_show">
	<img src="<%= @image.imgurl %>">
	<div class="image_info">
		<p> 
		<span>Image Title:</span> <%= @image.title %><br>
		<span>Width:</span> <%= @image.width %>,<br> 
		<span>Height:</span> <%= @image.height %><br>
		<span>File Size:</span> <%= @image.filesize %>
		</p>
	</div>
	
	<div class="url_container">
		Copy Image URL: <input type="text" name="url" value="<%= @image.imgurl %>" readonly>
	</div>

	<hr>

	<div id="color_block">
		<h2>Image's dominant colors</h2>
		<div id="all_colors">
			<!-- the below line makes an array containing 8 of the dominant colors from the image -->
			<% img = Miro::DominantColors.new("#{@image.imgurl}").to_hex %>
			<% img.each do |color| %>
					<div style="background-color: <%= color %> " class="single_color"> <span><%= color %></span> </div> 
			<% end %>
		</div>	
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Placehold.r</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<!-- class is set to that value because you want the class of the navbar to = what page the user is on -->
<header id='nav-<%= params[:controller]%>'>
	<!-- <img src="http://i.imgur.com/QwBNW0D.png" id="logo"> -->
	<ul id="navbar">
		<% if session[:current_user_id] %>
			<%= render partial: 'sessions/navbar', locals: { navbar: [:welcome, :profile, :home, :all_users, :all_boards, :search] } %>
		<% else %>
			<%= render partial: 'sessions/navbar', locals: { navbar: [:log_in, :sign_up, :home, :all_boards, :search] } %>
		<% end %>
	</ul>
</header>


<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<!-- this form will be used to add a new user and to edit an existing user -->
<%= form_for @user do |f| %>
  <div class="input">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="input">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
 </div>
  
  <div class="input">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
 </div>

<% if edit %>
  <div class="input">
    <%= f.label :avatar %>
    <%= f.text_field :avatar %>
 </div>
<% else %>
  <div class="input">
    <%= f.label :avatar %>
    <%= f.text_field :avatar, :value => 'http://www.placecage.com/200/200' %>
 </div> 
<% end %>


  
<% if new_user %>
  <div class="input">
    <%= f.label :password %>
    <%= f.password_field :password %>
 </div>
  
  <div class="input">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
<% end %>

<% if delete %>
  <div class="input" id="delete">
    <%= link_to "Delete User", user_path(@user), method: :delete %>
  </div>
<% end %>

  <%= f.submit "Submit", :id=>"submit" %>
<% end %>

app/views/users/_user.html.erb
	<!-- this page is used in users/index and users/show  -->
	<div class="thumb"><img src="<%= user.avatar %>"></div>
	<h4><%= user.username %></h4>

app/views/users/edit.html.erb
<div class="form splash" id="signup">

	<h1>Edit User</h1>
	<hr>
	<!-- this will show an error on edit form page if the form is not filled in with the requirements for user -->

	<% if @user.errors.any? %>
	  <div>
	    <h3 style="color:red">Please fix the appropriate fields:</h3>
	  </div>
	<% end %>

	<!-- shows user edit form -->
	<%= render partial: 'form', locals: { new_user: false, delete: true, edit: true } %>

</div>

app/views/users/index.html.erb
<div class="main_content users">

<h1>Members</h1>

	<div id="all_users">
		<% @users.each do |user| %>
			<div class="single">
				<%= link_to user_path(user) do %>
					<%= render user %>
				<% end %>
			</div>
		<% end %>
	</div>
	
</div>

app/views/users/new.html.erb
<div class="form splash" id="signup">

	<h1>New User</h1>

	<!-- shows errors on new form page if form is not filled in with requirements for new user, will not be allowed to create unless required fields are filled -->
	<% if @user.errors.any? %>
	    <h3 style="color:red">Please fix the appropriate fields:</h3>
	<% end %>

	<hr>
	<%= render partial: 'form', locals: { new_user: true, delete: false, edit: false } %>

</div>

app/views/users/show.html.erb
<div class="main_content user">
	<div class="bio">
		<h1>Profile</h1><br>
			<%= render partial: 'user', locals: { user: @user } %>
	<!-- on users/show if user is logged in there is a link on their show page to edit their user info, this is only allowed for the current user -->
		<% if current_user == @user %>
			<%= link_to "Edit User", edit_user_path(@user) %>
		<% end %>
	</div>

	<div class="cork_boards">
	<!-- displays all boards for this specific user -->
		<h1>My Cork Boards</h1>
		<% if current_user %>
			<%= render partial: '/boards/buttons', locals: {buttons: [:new_board]} %>
		<% end %>
			<div id="all_boards">
				<% @user.boards.each do |board| %>
					<%= render partial: '/boards/board', locals: {board: board} %>
					<hr>
				<% end %>
			</div>
	</div>
</div>